apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # label of deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
  # has its own meta data and spec
  # this config applies to a pod 
  # blueprint for a pod
    metadata:
      # label of pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080
