apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    # points to deployment or pod labels
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      # targetPort matches container port
      targetPort: 8080 
